### ISSUE TITLE
remove Serial to save RAM & flash

### ISSUE THREAD

**Issue by nerdralph** [daveruiz/doom-nano#1]
I noticed Serial is only used to display a debug message for the display library.
With the Arduino 1.8.9 IDE, removing Serial.begin & Serial.println saves 856 bytes of flash and 177 bytes of RAM.
Also, if you use the Uno, you get 1536 more bytes of flash due to the smaller bootloader.  Flashing Optiboot to a nano and using the Uno target will work the same.

**Comment by daveruiz** [comment]
Thanks for pointing it up! Yeah, It's there just for debug purposes, but it's clearly something that we can get rid of... And maybe use the same display if I need to debug.

I'm out of time lately, but will try to find some to keep it updated.

**Comment by daveruiz** [comment]
Resolved here https://github.com/daveruiz/doom-nano/commit/b1e59d6a07d1bcf2452706068f8e7f098cc56804
